### ISSUE TITLE
Update v1.0.0

### ISSUE THREAD

**Issue by ITakayuki** [itkyk/FTPController#10]
1. Change config file
  - `.env.template` -> `ftp.config.ts`
2. create `defineConfig` function
3. remove `ftp-deploy`
  - change non wrapper library

**Comment by ITakayuki** [comment]
## Todo  

- [x] .env.template -> ftp.config.ts
- [x] create defineConfig function
- [x] remove ftp-deploy
